# -*- coding: utf-8 -*-
"""Aula0311-sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xoxa556HIqeXjdzDKqxm5HO9yIPIYvhb
"""

from sklearn.neural_network import MLPClassifier
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

entradas = iris.data
saidas = iris.target

redeNeural = MLPClassifier(verbose=True, max_iter=1000, tol=0.001, activation='relu', solver='adam')
redeNeural.fit(entradas, saidas)

print(np.arange(redeNeural.n_iter_))

print(redeNeural.loss_curve_)

x=np.arange(redeNeural.n_iter_)
y=redeNeural.loss_curve_
from matplotlib.pyplot import *
plot(x,y)
xlabel("Iteração")
ylabel("erro")
show()

redeNeural.predict([[5, 7.2, 5.1, 2.2]])